# Generated by Django 5.1.6 on 2025-02-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_pong_id_rpsgame_rps_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsgame',
            name='rematch',
            field=models.BooleanField(default=False),
        ),
    ]
