# Generated by Django 5.1.6 on 2025-02-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rpsgame_rematch'),
        ('user', '0009_remove_users_jwt_token_remove_users_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponggame',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='ponggame',
            name='loser_score',
        ),
        migrations.RemoveField(
            model_name='ponggame',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ponggame',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='ponggame',
            name='winner_score',
        ),
        migrations.RemoveField(
            model_name='rpsgame',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='rpsgame',
            name='player1_choice',
        ),
        migrations.RemoveField(
            model_name='rpsgame',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='rpsgame',
            name='player2_choice',
        ),
        migrations.RemoveField(
            model_name='rpsgame',
            name='result',
        ),
        migrations.CreateModel(
            name='PongMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('pong_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ponggame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'unique_together': {('user_id', 'pong_id')},
            },
        ),
        migrations.CreateModel(
            name='RPSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveIntegerField(blank=True, null=True)),
                ('rps_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ponggame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'unique_together': {('user_id', 'rps_id')},
            },
        ),
    ]
