# Generated by Django 5.1.6 on 2025-02-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_ponggame_loser_remove_ponggame_loser_score_and_more'),
        ('user', '0010_alter_userstatistics_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rpsmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rpsmapping',
            name='rps_id',
        ),
        migrations.RemoveField(
            model_name='rpsmapping',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pong_player1', to='user.users'),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player1_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pong_player2', to='user.users'),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player2_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpsgame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rps_player1', to='user.users'),
        ),
        migrations.AddField(
            model_name='rpsgame',
            name='player1_choice',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rpsgame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rps_player2', to='user.users'),
        ),
        migrations.AddField(
            model_name='rpsgame',
            name='player2_choice',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='PongMapping',
        ),
        migrations.DeleteModel(
            name='RPSMapping',
        ),
    ]
