# Generated by Django 5.1.6 on 2025-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_rpsmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='player1_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player2_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rpsgame',
            name='player1_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rpsgame',
            name='player2_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
