# Generated by Django 5.1.6 on 2025-02-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_ponggame_player1_name_ponggame_player2_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponggame',
            old_name='player1',
            new_name='player1_id',
        ),
        migrations.RenameField(
            model_name='ponggame',
            old_name='player2',
            new_name='player2_id',
        ),
        migrations.RenameField(
            model_name='rpsgame',
            old_name='player1',
            new_name='player1_id',
        ),
        migrations.RenameField(
            model_name='rpsgame',
            old_name='player2',
            new_name='player2_id',
        ),
    ]
