# Generated by Django 5.1.6 on 2025-02-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_player1_ponggame_player1_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponggame',
            old_name='player1_id',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='ponggame',
            old_name='player2_id',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='rpsgame',
            old_name='player1_id',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='rpsgame',
            old_name='player2_id',
            new_name='player2',
        ),
    ]
