# Generated by Django 5.1.6 on 2025-02-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='intra_id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
