# Generated by Django 5.1.6 on 2025-02-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_users_intra_id_users_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='jwt_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pong_lose',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pong_win',
        ),
        migrations.RemoveField(
            model_name='users',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='rps_draw',
        ),
        migrations.RemoveField(
            model_name='users',
            name='rps_lose',
        ),
        migrations.RemoveField(
            model_name='users',
            name='rps_win',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tournament_win',
        ),
        migrations.RemoveField(
            model_name='users',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pong_win', models.PositiveIntegerField(default=0)),
                ('pong_lose', models.PositiveIntegerField(default=0)),
                ('rps_win', models.PositiveIntegerField(default=0)),
                ('rps_lose', models.PositiveIntegerField(default=0)),
                ('rps_draw', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
