# Generated by Django 5.1.6 on 2025-02-15 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_users_jwt_token_remove_users_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userstatistics', to='user.users'),
        ),
    ]
