# Generated by Django 5.1.6 on 2025-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userstatistics_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pong_lose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='pong_win',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='rps_draw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='rps_lose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='rps_win',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserStatistics',
        ),
    ]
